services:
  redis:
    container_name: redis
    image: hmctsprod.azurecr.io/imported/redis:8.2.1
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
volumes:
  redis:
    driver: local
